<h4><b>Asignatura:</b> Procesamiento Natural del Lenguaje.<br>
<b>Docente:</b> James Tomalá.<br>
<b>Institución:</b> IPP.<br>
<b>Fecha de Entrega:</b> 08 de Julio del 2026<br>
<b>Estudiante:</b> Jason Andrés Urrutia Orellana.</h4>

<h5><b>CONTEXTO:</b><em> Presentamos los resultados anteriores al equipo y obtenemos el
VoBo para continuar. Efectivamente, lo obtenido hasta el momento hace sentido, y
lo importante es que ya se cuenta con un corpus de comentarios limpio y se tiene un
vocabulario resumido. Alguien del equipo expresa que ya se puede aplicar, entonces,
un modelo para clasificación, por lo que -con todo la razón- argumentamos que
primero se debe obtener una representación vectorial del corpus, y justamente es lo
que se pondrá en foco a continuación.</em></h5>

<h2><b>CONSIGNAS</b></h2>

<p><b>1.</b><em> Se debe aplicar un modelo de representación
vectorial. Se recomienda el uso de TfidfVectorizer por sobre una representación BoW
debido a que facilita la inclusión de los emojis.</em></p>

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
comentarios = pd.read_csv("comentarios_procesados.csv")

In [3]:
comentarios.head()

,orden,comentario,tipo,tokens,lemmas,stems,texto_lemmas,texto_stems
0,1,"No les creo nada ,",malo,"['no', 'creo']","['no', 'creer']","['no', 'cre']",no creer,no cre
1,2,Está bonita la camioneta,bueno,"['bonita', 'camioneta']","['bonito', 'camioneto']","['bonit', 'camionet']",bonito camioneto,bonit camionet
2,3,Quiero más información,info,"['quiero', 'información']","['querer', 'información']","['quier', 'inform']",querer información,quier inform
3,4,:( igual el crédito ha de ser muuuucho,malo,"[':(', 'igual', 'crédito', 'ser', 'muuuucho']","[':(', 'igual', 'crédito', 'ser', 'muuuucho']","[':(', 'igual', 'credit', 'ser', 'muuuuch']",:( igual crédito ser muuuucho,:( igual credit ser muuuuch
4,5,"Quisiera, más información, pero nadie me respo...",info,"['quisiera', 'información', 'nadie', 'responde']","['querer', 'información', 'nadie', 'responder']","['quis', 'inform', 'nadi', 'respond']",querer información nadie responder,quis inform nadi respond

In [4]:
comentarios.info

<bound method DataFrame.info of      orden                                         comentario   tipo  \
0        1                                No les creo nada ,    malo
1        2                          Está bonita la camioneta   bueno
2        3                             Quiero más información   info
3        4            :( igual el crédito ha de ser muuuucho    malo
4        5  Quisiera, más información, pero nadie me respo...   info
..     ...                                                ...    ...
595    596  piezas de respuestos escasas y demoran mucho e...   malo
596    597                    No sube muy bien las pendientes   malo
597    598                     es la mejor SUV que he tenido   bueno
598    599                el crédito directo resulta muy caro   malo
599    600                      la recomiendo a ojos cerrados  bueno

                                                tokens  \
0                                       ['no', 'creo']
1                              ['bonita', 'camioneta']
2                            ['quiero', 'información']
3        [':(', 'igual', 'crédito', 'ser', 'muuuucho']
4     ['quisiera', 'información', 'nadie', 'responde']
..                                                 ...
595  ['piezas', 'respuestos', 'escasas', 'demoran',...
596        ['no', 'sube', 'muy', 'bien', 'pendientes']
597                                   ['mejor', 'suv']
598   ['crédito', 'directo', 'resulta', 'muy', 'caro']
599                 ['recomiendo', 'ojos', 'cerrados']

                                                lemmas  \
0                                      ['no', 'creer']
1                              ['bonito', 'camioneto']
2                            ['querer', 'información']
3        [':(', 'igual', 'crédito', 'ser', 'muuuucho']
4      ['querer', 'información', 'nadie', 'responder']
..                                                 ...
595  ['pieza', 'respuesto', 'escaso', 'demorar', 't...
596      ['no', 'subir', 'mucho', 'bien', 'pendiente']
597                                   ['mejor', 'suv']
598  ['crédito', 'directo', 'resultar', 'mucho', 'c...
599                     ['recomeir', 'ojo', 'cerrado']

                                             stems  \
0                                    ['no', 'cre']
1                            ['bonit', 'camionet']
2                              ['quier', 'inform']
3      [':(', 'igual', 'credit', 'ser', 'muuuuch']
4            ['quis', 'inform', 'nadi', 'respond']
..                                             ...
595  ['piez', 'respuest', 'escas', 'demor', 'tra']
596       ['no', 'sub', 'muy', 'bien', 'pendient']
597                               ['mejor', 'suv']
598   ['credit', 'direct', 'result', 'muy', 'car']
599                      ['recom', 'ojos', 'cerr']

                                texto_lemmas                    texto_stems
0                                   no creer                         no cre
1                           bonito camioneto                 bonit camionet
2                         querer información                   quier inform
3              :( igual crédito ser muuuucho    :( igual credit ser muuuuch
4         querer información nadie responder       quis inform nadi respond
..                                       ...                            ...
595  pieza respuesto escaso demorar traer él  piez respuest escas demor tra
596            no subir mucho bien pendiente       no sub muy bien pendient
597                                mejor suv                      mejor suv
598      crédito directo resultar mucho caro   credit direct result muy car
599                     recomeir ojo cerrado                recom ojos cerr

[600 rows x 8 columns]>

In [5]:
comentarios[["texto_lemmas", "tipo"]].head()

                         texto_lemmas   tipo
0                            no creer   malo
1                    bonito camioneto  bueno
2                  querer información   info
3       :( igual crédito ser muuuucho   malo
4  querer información nadie responder   info

In [6]:
x = comentarios["texto_lemmas"]
y = comentarios["tipo"]

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [8]:
vectorizador = TfidfVectorizer()

In [9]:
x_train_tfidf = vectorizador.fit_transform(x_train)
x_test_tfidf = vectorizador.transform(x_test)

In [10]:
print(f"(cantidad de comentarios, términos únicos) train: {x_train_tfidf.shape}")
print(f"(cantidad de comentarios, términos únicos) test: {x_test_tfidf.shape}")

(cantidad de comentarios, términos únicos) train: (480, 244)
(cantidad de comentarios, términos únicos) test: (120, 244)

In [11]:
vocabulario = vectorizador.get_feature_names_out()
print(vocabulario)

['además' 'ahora' 'alto' 'amar' 'amigo' 'anterior' 'app' 'aprovechar'
 'asiento' 'así' 'auto' 'año' 'bajen' 'bajo' 'barra' 'bellisimooo' 'bien'
 'bonito' 'buen' 'bueno' 'cada' 'calidad' 'cambio' 'camioneto' 'cara'
 'carisimo' 'caro' 'carretero' 'cero' 'cerrado' 'chico' 'china' 'chino'
 'claro' 'cobrar' 'colocar' 'combuestible' 'combustible' 'comodidad'
 'completo' 'compr' 'compra' 'comprar' 'confianza' 'confort' 'conocer'
 'conseguir' 'consumo' 'contado' 'contar' 'contento' 'corrida'
 'cotización' 'creer' 'crédito' 'cual' 'cumplir' 'cuota' 'cuoton' 'cuándo'
 'cuánta' 'cuánto' 'cómo' 'cómodo' 'dar' 'dato' 'dañado' 'dañar' 'decir'
 'deficiente' 'definitvamente' 'demasiado' 'demoran' 'demorar' 'detalle'
 'devolver' 'directo' 'diseño' 'doble' 'duda' 'día' 'elección' 'embrague'
 'encantar' 'encanto' 'engañoso' 'escaso' 'espacio' 'espectacular'
 'estable' 'estrellas' 'excelente' 'excesivamente' 'existir' 'experiencia'
 'explicártelo' 'fa' 'fabricado' 'fallar' 'favor' 'fiel' 'final'
 'finalmente' 'financiamiento' 'fortuna' 'fácil' 'galón' 'gasolinar'
 'gente' 'gracias' 'gradia' 'gran' 'grande' 'gustar' 'hacer' 'hermoso'
 'holar' 'híbrido' 'igual' 'info' 'información' 'inseguro' 'inteligente'
 'interesa' 'interior' 'interso' 'interés' 'iva' 'joyo' 'kilómetro' 'km'
 'letra' 'mal' 'malo' 'mandar' 'manejar' 'mantención' 'maravilla'
 'maravilloso' 'marca' 'marcar' 'mas' 'mayo' 'mayor' 'mayot' 'mecánico'
 'mejor' 'mentirós' 'mercado' 'mes' 'mil' 'millón' 'modelo' 'mucho'
 'muuuucho' 'méxico' 'nadie' 'necesitar' 'necesito' 'ninguno' 'no' 'nub'
 'oferta' 'ojo' 'pagar' 'pagu' 'pantalla' 'parecer' 'paseo' 'pedir'
 'pendiente' 'peor' 'perfecto' 'pie' 'pieza' 'poco' 'poder' 'poner'
 'precio' 'preferir' 'presentación' 'primero' 'problema' 'producto'
 'publicidad' 'pésimo' 'quedar' 'querer' 'realizar' 'realmente' 'recién'
 'recomeir' 'recomendable' 'rendimiento' 'rendir' 'reparación' 'repuesto'
 'responder' 'respuesto' 'resultar' 'saber' 'sacar' 'salido' 'salir'
 'saludo' 'seguir' 'seguirar' 'seguridad' 'seguro' 'ser' 'serivicio'
 'servicio' 'sevicio' 'si' 'solo' 'stok' 'suave' 'subir' 'superior' 'suv'
 'tecnología' 'teconlogío' 'tema' 'tendrar' 'terminar' 'tesoro' 'todo'
 'traer' 'tremendo' 'táctil' 'técnico' 'tú' 'uses' 'valor' 'vehículo'
 'vender' 'venir' 'ver' 'versión' 'vez' 'weá' 'yo' 'él' 'último']

In [12]:
def mostrar_tfidf(orden):
    # Esta función permitirá ingresar un índice de comentario, y obtendrá por respuesta
    # el peso tfidf de cada una de sus palabras que le componen
    fila = comentarios[comentarios["orden"] == orden]
    if fila.empty:
        print("Comentario no encontrado, por favor, ingrese otro valor")
        return
    texto = fila["texto_lemmas"].iloc[0]
    categoria = fila["tipo"].iloc[0]
    vector = vectorizador.transform([texto])
    tfidf = pd.DataFrame({
        "Palabra": vectorizador.get_feature_names_out(),
        "Peso TF-IDF": vector.toarray().flatten()
    })
    tfidf = (
        tfidf[tfidf["Peso TF-IDF"] > 0]
        .sort_values(by="Peso TF-IDF", ascending=False)
        .reset_index(drop=True)
    )
    print("=" * 80)
    print(f"Comentario N° {orden}")
    print(f"Categoría: {categoria}")
    print("-" * 80)
    print(texto)
    print("=" * 80)
    return tfidf

In [13]:
"""Ingresar un valor del 1 al 600 (cantidad de comentarios) para obtener un rápido análisis del mismo"""
mostrar_tfidf(95)

================================================================================
Comentario N° 95
Categoría: malo
--------------------------------------------------------------------------------
mucho mal sevicio mantención
================================================================================

      Palabra  Peso TF-IDF
0         mal     0.583420
1     sevicio     0.583420
2  mantención     0.491201
3       mucho     0.279222

<p><b>insight importante:</b> Durante la exploración del corpus se identificaron comentarios repetidos dentro del dataset. Estos registros fueron conservados para mantener la estructura original del conjunto de datos.</p>